name:   quake-shareware
version:        "0.2"
summary:        Quake shareware installer
description:    |
        Quake is a classic First Person Shooter, originally released by id games. This will install the shareware version which will be launched in the quakespam engine.
confinement:    strict
grade: stable

apps:
        quake-shareware:
                command: launcher
                plugs:  [unity7, pulseaudio, opengl, network]

parts:
        sdlgui:
                plugin: autotools
                source-type:    tar
                source: https://www.libsdl.org/projects/GUIlib/src/GUIlib-1.2.1.tar.gz
                configflags: [--prefix=/usr]
                build-packages:
                        - gcc
                        - g++
                        - make
                        - libsdl1.2-dev
        gui:
                after: [sdlgui]
                plugin: autotools
                source: guisrc
                configflags: [--prefix=/usr]
                build-packages:
                        - gcc
                        - make
                        - libsdl1.2-dev
        quakespasm:
                plugin: make
                source: svn://svn.code.sf.net/p/quakespasm/code/trunk/quakespasm
                source-subdir: Quake
                make-parameters:
                        - USE_SDL2=1
                artifacts:
                        - quakespasm
                        - quakespasm.pak
                build-packages:
                        - gcc
                        - make
                        - libsdl2-dev
                        - libmad0-dev
                        - libogg-dev
                        - libvorbis-dev
                stage-packages:
                        - libsdl2-2.0-0
                        - libmad0
                        - libogg0
                        - libvorbis0a
        launch:
                plugin: dump
                source: launcher
                stage-packages:
                        - wget
                        - unzip
                        - libpng12-0
                        - libsdl1.2debian
                        - libgl1-mesa-glx
                prime:
                        - -share
                        - -usr/share/doc
                        - -usr/share/lintian
                        - -usr/share/man
