#!/bin/bash

set -e

GAMEDIR=quake_shareware

if [ ! -d $SNAP_USER_DATA/$GAMEDIR/shareware ];
then
  echo "Game directory doesn't exist"
  echo "Creating directory"
  mkdir -p $SNAP_USER_DATA/$GAMEDIR
  echo "Copying game to directory"
  cd $SNAP_USER_DATA/$GAMEDIR
  guiluurve download
  wget https://archive.org/download/Quake_802/zQUAKE_SW-play.zip -t 5 --timeout 10 || guiluurve nodownload
  unzip -LL -d shareware zQUAKE_SW-play.zip || guiluurve nozip
  cp $SNAP/quakespasm.pak $SNAP_USER_DATA/$GAMEDIR/shareware
fi

cd $SNAP_USER_DATA/$GAMEDIR
${SNAP}/quakespasm -f -basedir shareware
