name: quake-shareware
version: "qs-0.93.2"
summary: Quake shareware installer
description: |
  Quake is a classic First Person Shooter, originally released by id games. This will install the shareware version which will be launched in the quakespasm engine.
confinement: strict
grade: stable
base: core18

apps:
  quake-shareware:
    command: launcher
    plugs: [unity7, pulseaudio, opengl, network, joystick]
    extensions: [gnome-3-28]

parts:
  quakespasm:
    plugin: make
    source-type: tar
    source: https://downloads.sourceforge.net/project/quakespasm/Source/quakespasm-0.93.2.tgz
    source-subdir: Quake
    make-parameters:
      - USE_SDL2=1
    artifacts:
      - quakespasm
      - quakespasm.pak
    build-packages:
      - gcc
      - make
      - libsdl2-dev
      - libmad0-dev
      - libogg-dev
      - libvorbis-dev
    stage-packages:
      - libsdl2-2.0-0
      - libmad0
      - libogg0
      - libvorbis0a
      - libpng16-16
      - libgl1-mesa-glx
      - libglu1-mesa
      - libvorbisfile3
  launch:
    plugin: dump
    source: launcher
    stage-packages:
      - wget
      - unzip
      - yad
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk-3-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  cleanup:
    after: [quakespasm, launch]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
